### ISSUE TITLE
Print path to file containing failed test

### ISSUE THREAD

**Issue by AlexBaranosky** [marick/Midje#115]
[Moved here from: https://github.com/marick/lein-midje/issues/19]

Test output for a failed test is something along the lines of:

`FAIL at (package_version.clj:38)`

It would be helpful if the file contained either the full or relative path. Reason being is that with noir projects you might have multiple files with the same name but under different paths say for views, models etc..

If you point me in the right direction I'll do the change and submit a pull request if you would like.

**Comment by marick** [comment]
Adopting a policy of "if it hasn't happened by now, it will either happen in 2.0 or never", I'm closing this
