### ISSUE TITLE
Metaconstants are different

### ISSUE THREAD

**Issue by prepor** [marick/Midje#159]
Hello! I expected, that this fact should be right.

``` clojure
(unfinished get-doc)
(defn get-id []
  (:id (get-doc)))

(fact
  (get-id) => 1
  (provided
      (get-doc) => ..doc..
      ..doc.. =contains=> {:id 1}))
```

But `..doc..` containing `:id` and `..doc..` returning by `(get-doc)` are different objects, so fact failed with 

```
    Expected: 1
      Actual: ni
```

I was expecting the wrong behavior?

**Comment by phillipm** [comment]
addressed in https://github.com/marick/Midje/issues/390
