### ISSUE TITLE
Need to expand metaconstant's notion of equality

### ISSUE THREAD

**Issue by marick** [marick/Midje#160]
```
        Actual result: java.lang.Error: Metaconstants (..new-interval..) can't be compared for equality with :pause.
```

The Midje `autotest` function can be called like this:

``` clojure
(autotest :pause)
(autotest :interval 5 :dirs ["test"])
```

There is a test like this:

```
(fact (autotest :dirs ..new-dirs.. :interval ..new-interval..) ...)
```

That blows up because the code has this comparison:

``` clojure
((set args) :pause)
```

Since a metaconstant is in the arglist, it gets compared against a keyword. Boom. 

Metaconstant equality, I think now, should succeed in general and return false.

**Comment by phillipm** [comment]
Given that the following test example passes, I think this has been fixed

```
(fact
  (#{..foo..} :random-key) => nil 
  (provided ..foo.. =contains=> {:a 1}))
```
