### ISSUE TITLE
Formatting / lein midje and the clojure.test output

### ISSUE THREAD

**Issue by josephwilk** [marick/Midje#179]
The current output for midje when run through lein confuses me:

```clojure
$ lein midje
FAIL "reporting on a type mismatch" at (t_chatty.clj:168)
    Expected: {:x 1, :y 2}
      Actual: {:x 1, :y 2}
>>> Output from clojure.test tests:

[GREEN]0 failures, 0 errors.[/GREEN]
>>> Midje summary:
[RED]FAILURE:[/RED] 1 prediction did not come true.  (But 2582 did.)
```
The counts from clojure.test never seem to catch that there were errors.

The green from clojure.test (everything went well) and the red from Midje (there was an error) contradict each other which is confusing!

Whats the purpose of the clojure.test output? 
Is it needed?

**Comment by marick** [comment]
Adopting a policy of "if it hasn't happened by now, it will either happen in 2.0 or never", I'm closing this
