### ISSUE TITLE
"after :contents" doesn't work with namespace-state-changes

### ISSUE THREAD

**Issue by philc** [marick/Midje#214]
I would expect this code snippet

```
(do
  (namespace-state-changes (before :contents (println "before contents"))
                          (after :contents (println "after contents")))
  (fact "one" (println "during 1") => nil))
```

to print

"before contents"
"during 1"
"after contents"

but it actually prints
"before contents"
"after contents"
"during 1"

I realize using :contents with namespace-state-changes is conceptually murky. If this behavior is by design, we should document it.

**Comment by urzds** [comment]
Currently we use (a thin wrapper around) `(mount/start)` at the beginning of the namespace and `(mount/stop)` at its end. There appear to be problems with `(mount/stop)` not being executed in case of exceptions, when tests abort. I was hoping that `(namespace-state-changes)` [1] would be able to solve this issue, but the lack of `(after :contents ...)` support makes it unusable in this case.

[1]: Or `(background)`? Which one is the real thing? Both appear appear to be recommended by the documentation:
* https://github.com/marick/Midje/wiki/Setup-and-teardown
* https://github.com/marick/Midje/wiki/Setup,-Teardown,-and-State

**Comment by devurandom** [comment]
> Maybe your tests should wrap the loading of the namespace with something that calls `mount/stop`?

How? Could you give a short example that explains how I wrap the loading of a namespace? Maybe I can continue from there and learn how to combine that with `mount` and `midje`.

**Comment by marick** [comment]
My Clojure is really rusty, but something like 

```clojure
(try 
  (mount/start)
  (load "test-namespace.clj")
(finally 
  (mount/stop)))
```
