### ISSUE TITLE
Config option to control whether clojure.test tests are run

### ISSUE THREAD

**Issue by dkincaid** [marick/Midje#224]
From the Midje Google group:

>         • By default calling (load-tests) seems to run clojure.test tests as well as the Midje facts. Is there a way to turn this off so that the clojure.test tests can be run separately in the process I've already created for that purpose? 

Not now. You can however, hack or hook midje.emission.clojure-test-facade/run-tests to make it do nothing. This should probably be a config option. Would you file an issue so that I know to add it?

**Comment by codeitagile** [comment]
I can't find this on the Trello board. If I could I would up-vote it. I want to categorise tests as unit or integration tests and run those in isolation of one another.

**Comment by marick** [comment]
Adopting a policy of "if it hasn't happened by now, it will either happen in 2.0 or never", I'm closing this
