### ISSUE TITLE
Is there a way of labelling tests like you would label equations in latex?

### ISSUE THREAD

**Issue by zcaudate** [marick/Midje#233]
I would like to have a way of putting my documentation along with the tests so that section numbers and function numbers are automatically generated. I'm happy to hack on this feature if someone can tell me where to start looking to do this. 

The code that's want to write looks something like this:

(fact  "section 1"
     "this is an example of division:"
     (label "one")
     (/ 2 2) => 1

      "refer to Eq {{one}} for the example")

And it should generate markdown to look something like this:

----------

# section 1

this is an example of division:

    (/ 2 2) => 1               Eq 1.1

Refer to Eq 1.1 for the example

**Comment by marick** [comment]
I think this is outside the scope of Midje.
