### ISSUE TITLE
fact => syntax screws up Clojure indenting (with possible solution)

### ISSUE THREAD

**Issue by Profpatsch** [marick/Midje#235]
Due to the fact that

``` clojure
(fact
  expr => result
  expr => result))
```

is very un-lisp-y, every indenting algorithm gets completely screwed up by this.

Plus, it’s hard to read when statements get more complex, because it’s a break in normal Clojure syntax.

I recommend adding a pair of brackets around the arrow statements, like this:

``` clojure
(fact
  [expr => result]
  [expr => result])
```

Reasoning for brackets and against parentheses: With parentheses, the first element has a special meaning. In brackets all elements are of equal standing (function call vs array).

Another possibility would be to do it in a `let`-like manner:

``` clojure
(fact
  [expr => result
   expr => result])
```

This could be harder to comprehend when the `expr` and `result`s get bigger, though.

All in all, introducing these brackets makes the macro notation lisp-y and indentation-compatible.

**Comment by rafaeldff** [comment]
wontfix

**Comment by Profpatsch** [comment]
Clojure still exists?
