### ISSUE TITLE
1.6.0: tabular gets confused about substitutions

### ISSUE THREAD

**Issue by gmorpheme** [marick/Midje#262]
```
(facts "blah"
  (let [init 1
        x-false {:a 1}
        x-true {:a 2}
        apply-f (fn [state f] (f state))]
    (tabular
     (fact (apply-f ?state ?f) => ?check)

     ?state    ?f                                 ?check
     x-false   #(update-in % [:a] inc) (contains {:a 2})
     x-false   #(update-in % [:a] inc) (contains {:a 2})
     x-false   #(update-in % [:a] inc) (contains {:a 2}))))
```

With < 3 rows it works (maybe by chance). It seems with 3 or more rows it fails because the substitutions are out of sync.

FAIL "blah" at (vm_test.clj:204)
With table substitutions: [?state (contains {:a 2})
                           ?f x-false
                           ?check (fn\* [p1__14166#](update-in p1__14166# [:a] inc))
                           x-false (contains {:a 2})]
Actual result did not agree with the checking function.
        Actual result: nil
    Checking function: (fn\* [p1__14166#](update-in p1__14166# [:a] inc))

Removing the outer facts seems to fix it.

Maybe I'm not using tabular correctly but it was working for me in 1.5.

**Comment by phillipm** [comment]
fixed and released in `1.9.3-alpha2`
