### ISSUE TITLE
Midje messes up comparison of sets with vectors containing the same number of elements with different types.

### ISSUE THREAD

**Issue by ohcibi** [marick/Midje#265]
Consider the following snippet:

``` clojure
(ns my-ns.core-test
  (:use midje.sweet))

(defn test-f [s] #{[1 2 3] [:a :b :c]})

(facts "some facts"
       (fact "a fact"
             (test-f []) => #{}))
```

This fails with the error `java.lang.ClassCastException: java.lang.Long cannot be cast to clojure.lang.Keyword`.

I experimented a bit and found out that, regarding the numbers in the vectors of the set which is returned from test-f:

a) the number of elements must be the same
b) the type of the elements must differ

For this error to happen. When the number is different or both vectors contain only integers, I get a normal error message like:

```
FAIL "some facts - a fact" at (core_test.clj:11)
    Expected: #{}
      Actual: #{[1 2 3 4] [5 2 3 4]}
FAILURE: 1 check failed.
```

Additionally the number of checks that are reported as failed is **2** instead of **1** when the above error happens (running lein midje :autotest).

This happens with `lein midje` as well as with `lein midje :autotest`. Is this an issue of lein-midje or midje itself?

**Comment by phillipm** [comment]
addressed in https://github.com/marick/Midje/issues/391
