### ISSUE TITLE
`provided` stubs explode if functions are type hinted with primitive types

### ISSUE THREAD

**Issue by nukemberg** [marick/Midje#295]
``` clojure
(ns type-hint-test
  (:use midje.sweet))

(defn test-fn [^long x] x) ; primitive type

(defn do-something [x] (test-fn x))

(fact "when stubing `test-fn` this shouldn't blow up"
      (do-something ..test..) => ..test..
      (provided
       (test-fn ..test..) => ..test..))
```

This example blows up with `java.lang.ClassCastException: clojure.lang.AFunction$1 cannot be cast to clojure.lang.IFn$LO`

**Comment by dangitall** [comment]
Any more thoughts on this? Can there be a way to indicate that metaconstants can be of a certain primitive type?

**Comment by marick** [comment]
From what little I know of type-hinting, I don't think there's a mechanism to tell Clojure "treat this `deftype Metaconstant` as some other type."

The idea behind a metaconstant is that all that can be known about them is:
1. two metaconstants with the same name are equal.
2. any `provided` expressions are defined to be true.

They're something like a [bottom type](https://en.wikipedia.org/wiki/Bottom_type) where test-specific properties are added on. Tagging them with a specific type would involve implicitly giving them a whole lot of properties.

**Comment by viebel** [comment]
Can you guys think of a workaround when the function to mock is defined with type hints?

**Comment by philomates** [comment]
Hey @viebel, I did find this hack http://www.tianxiangxiong.com/2017/03/18/clojure-with-redefs-gotcha.html

so the following seems to work

```clojure
(defn test-fn [^long x] (+ x 1)) ; primitive type

(defn do-something [x] 
 ;; CHANGE MADE HERE: turn (test-fn x) to (#'test-fn x)
  (#'test-fn x))

(with-redefs [test-fn (fn [x] (prn :x x) x)]
  (do-something "non-int"))
```

I would be curious to hear people deep in the clojure internals talk about this gotcha

**Comment by viebel** [comment]
I'll put here my use case, for the record:

This code causes an exception:
~~~clojure
(defn bar [^String x ^long x])
(defn foo []
  (bar "a" 1))

(fact
 (foo ) => nil
 (provided (bar "a" 1) => nil))
~~~

~~~
java.lang.ClassCastException: clojure.lang.AFunction$1 cannot be cast to clojure.lang.IFn$OLO
~~~

While this code works as expected
~~~clojure
(defn bar [^String x ^long x])
(defn foo []
  (#'bar "a" 1))

(fact
 (foo ) => nil
 (provided (bar "a" 1) => nil))
~~~
