### ISSUE TITLE
Documentation for 'expect'

### ISSUE THREAD

**Issue by jjl** [marick/Midje#308]
My test was failing because I was using a function called 'expect'. I can't seem to find anywhere in the documentation that urges caution of using that name. Having looked through the midje code, I see it's a basic building block on which much is built, so it seems like it's worth documenting.

**Comment by marick** [comment]
Sorry for the delay.

Actually, I think the correct approach is for `expect` not to be exported from `midje.sweet`.

**Comment by jjl** [comment]
Sounds like a reasonable option to me. I'll have a stab at fixing it when I'm more awake.

**Comment by marick** [comment]
`expect` will remain an internal detail and probably go away in 2.0
