### ISSUE TITLE
defprotocol/defrecord best practice

### ISSUE THREAD

**Issue by dmitrig01** [marick/Midje#309]
Hey! I have the following situation:

a.clj:
```clojure
(ns a)
(defprotocol A (a [_]))
```

b.clj:
```clojure
(ns b
  (:require [midje.open-protocols :refer [defrecord-openly]]
            [a :refer [A]]))

(defrecord-openly B []
  A
  (a [_] (prn "something")))
```

now, compilation fails, ecause defrecord-openly transforms it into:
```clojure
(clojure.core/defrecord B []
 A
 (a
  [_]
  (if
   (midje.data.prerequisite-state/implements-a-fake? a) ; <-- obviously "a" is not defined here
   (clojure.core/apply a [_]) ; <-- nor here
   (do (prn "something")))))
```

What is the best practice here? I could just `:use a`, but I thought the best practice was to `:require` instead?

**Comment by marick** [comment]
In researching this, I've learned something I didn't know about protocols (and later versions of Clojure). I've documented that background in a [series of examples](https://github.com/marick/Midje/tree/master/test/as_documentation/about_defrecord). The last one is perhaps the answer to your question.

The way `defrecord-openly` expands is probably incorrect, though I don't anticipate fixing it soon.

**Comment by dmitrig01** [comment]
you are awesome

**Comment by marick** [comment]
And good looking, too!
