### ISSUE TITLE
Checking function is called twice

### ISSUE THREAD

**Issue by klauswuestefeld** [marick/Midje#317]
```
(fact "Checking function is called twice"
  1 => (fn [x] (do (println "YES" x) true))
  2 => (fn [x] (do (println "NO" x) false)))

Result:
YES 1
NO 2
NO 2
```

The checking function is called twice when it doesn't match. That's really confusing when debugging. It made me think my code was running twice by mistake.

Thanks, Klaus

**Comment by marick** [comment]
I apparently agreed with you several years ago:

```clojure
                             ;; TODO: It is very lame that the
                             ;; result-function has to be called again to
                             ;; retrieve information that extended-=
                             ;; knows and threw away. But it's surprisingly
                             ;; difficult to use evaluate-checking-function
                             ;; at the top of the cond
```

I'm gradually working up the infrastructure behind Midje 2.0. Using Specter for parsing - and generally being a better Clojure programmer these days - should avoid such glitches.

**Comment by klauswuestefeld** [comment]
Nice :)

**Comment by phillipm** [comment]
addressed in https://github.com/marick/Midje/issues/395
