### ISSUE TITLE
Improve nomenclature by preferring "includes" over "contains"

### ISSUE THREAD

**Issue by MerelyAPseudonym** [marick/Midje#320]
E.g., `(fact [4 5 6] =includes=> 5)` instead of `(fact [4 5 6] =contains=> 5)`.

The reason would be to avoid exacerbating the problem of people tripping over the meaning of `clojure.core/contains?`, which is a _notorious_ gotcha.

By the way, I'm mainly trying to test the ideological waters here—I'm perfectly happy doing the legwork provided you're open to the change.

**Comment by phillipm** [comment]
I agree with you, but at this point I would like to avoid introducing new names for older midje constructs because that has caused quite a bit of confusion in the past
