### ISSUE TITLE
Midje autotest fails when ring.middleware.reload library and :reload-all flag are used together

### ISSUE THREAD

**Issue by emrehan** [marick/Midje#321]
Hi,

I'm using Mac OS X and Clojure 1.7.

Midje autotest has stopped working for me for a week. I've tried the lein flag and the repl command. I've also them it in iTerm and Terminal.

It used to work almost as expected until a week ago. By almost what I mean is when I chanced a line in a file it didn't react from time to time. Now it doesn't react even I put new files or make huge changes.

I'm getting a lot of reflection warnings, could these help spotting the issue?

**Comment by marick** [comment]
What version of Midje are you using? Had you upgraded Midje or Clojure or OSX recently? Can you reproduce the problem in a stripped-down project, perhaps a fork of https://github.com/marick/sample-midje-project ?

**Comment by emrehan** [comment]
Hi, 

I'm using Midje 1.7.0. 

I don't think I've upgraded any of them recently to cause this problem. 

I'll try to reproduce the error on the sample project this week. Hopefully putting all of my dependencies would reproduce the error :)

**Comment by emrehan** [comment]
I've reproduced the error: https://github.com/emrehan/failing-midje

**Comment by marick** [comment]
Interesting. I note that ring.middleware.reload uses nstracker, which uses clojure.tools.namespace. Midje uses clojure.tools.namespace directly. So my first reaction is that nstracker is first noticing that a file's changed, reloading it, and thus somehow preventing Midje-via-clojure.tools.namespace from noticing the change. However, looking into the various sources, I don't see how nstracker could be smashing any state that clojure.tools.namespace depends upon.

But: I don't offhand see how ring.middleware.reload works. What is it in the `require` process that actually starts the change tracking? In the following:

```clojure
  (:require [ring.middleware.reload :as reload] :reload-all))
```

... what purpose is the `:reload-all` serving? Either I'm missing something obvious, or there's Rails-style magic going on.

**Comment by emrehan** [comment]
`:reload-all` workarounds this bug: http://dev.clojure.org/jira/browse/CLJ-1544. Without it compilation gives the following error: `java.lang.NoClassDefFoundError: clojure/tools/logging/impl/LoggerFactory`.

**Comment by marick** [comment]
@emrehan Is there anything that can be done to avoid this problem in autotest. (I don't know AOT, because every time I start to use it, everything breaks.)

**Comment by emrehan** [comment]
No I can't make them work together. But if that issue has nothing to do with Midje you can close it.

**Comment by marick** [comment]
I'm at a loss for what I can do to avoid it. But I'll leave this open for a while as a reminder.
