### ISSUE TITLE
Metadata not inherited when nesting facts

### ISSUE THREAD

**Issue by joelittlejohn** [marick/Midje#322]
Imagine the following facts:

``` clj
(fact
 :foo "foo tests wont run"
 (fact "bar" 1 => 1)
 (fact "baz" 1 => 1))

(fact
 :foo "foo tests will run"
 (fact :foo "qux" 1 => 1)
 (fact :foo "quux" 1 => 1))
```

The docs state that the metadata of the parent fact is inherited by children, and that metadata on the children is ignored. When I run the following:

`lein midje :filter foo`

I expect all 4 facts to be run, but only 2 facts ("qux" and "quux") are run.

**Comment by marick** [comment]
Fixed. It will take me a bit before I get a new version out.

**Comment by joelittlejohn** [comment]
Thanks Brian, you're a legend!
