### ISSUE TITLE
clojure 1.7.0 :  several warnings

### ISSUE THREAD

**Issue by rwobben** [marick/Midje#324]
Hello, 

When I use lein-midje 3.2-rc4 , clojure 1.7 and I do lein midje I see these warnings : 

WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.core, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.2-to-lexical-maps.fakes, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.util.fnref, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.util.error-handling, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.lexical-maps, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.3-from-lexical-maps.from-fake-maps, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checkers, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.chatty, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.util, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.simple, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.collection, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.collection-util, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.collection-comparison, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.predictions, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.util.laziness, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.1-to-explicit-form.background, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.util.wrapping, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.2-to-lexical-maps.data-fakes, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.2-to-lexical-maps.expects, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.doc, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.0-to-fact-form.tabular, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.1-to-explicit-form.facts, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.data.compendium, being replaced by: #'midje.clojure.core/record?
WARNING: update already refers to: #'clojure.core/update in namespace: utilize.map, being replaced by: #'utilize.map/update
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.0-to-fact-form.formulas, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.data.project-state, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.other.arglists, being replaced by: #'midje.clojure.core/record?

**Comment by marick** [comment]
What version of Midje are you using? It doesn't happen with this project.clj file:

```clojure
(defproject scratch "1.0.0-SNAPSHOT"
  :description "FIXME: write"
  :dependencies [[org.clojure/clojure "1.7.0"]]
  :profiles {:dev {:dependencies [[midje "1.7.0"]]}}
  :plugins [[lein-midje "3.2-RC4"]])
```

**Comment by rwobben** [comment]
I have to change the project.clj file which looks like this now : 
 
~~~

(defproject training-day "1.0.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [iloveponies.tests/training-day "0.1.0-SNAPSHOT"]]
  :profiles {:dev {:plugins [[lein-midje "3.2-RC4"]]}})

**Comment by rwobben** [comment]
When I change it to : 

~~~

(defproject training-day "1.0.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [iloveponies.tests/training-day "0.1.0-SNAPSHOT"]]
  :profiles {:dev {:dependencies [[midje "1.7.0"]]}}
  :plugins [[lein-midje "3.2-RC4"]])

 ~~~

no error messages are seen.
Thanks for the help.
