### ISSUE TITLE
question : can I run a test on one function

### ISSUE THREAD

**Issue by rwobben** [marick/Midje#325]
Hello, 

Im doing now this course : https://github.com/rwobben/structured-data
all the exercises are in src and the test in test.

Now I wonder if I could test only 1 function with midje.
If it can, how do I do this .?

Roelof

**Comment by marick** [comment]
You can use the repl tools to test a single function: https://github.com/marick/Midje/wiki/Repl-tools

I personally use in-repl autotest https://github.com/marick/Midje/wiki/Autotest

These questions are probably better asked in the mailing list: https://groups.google.com/forum/#!forum/midje
