### ISSUE TITLE
Wiki lacks documentation on provided

### ISSUE THREAD

**Issue by shmish111** [marick/Midje#326]
One of the features we use most is the `provided` form however it is very difficult to find information about it in the Wiki.  For example, [this](http://stackoverflow.com/questions/20234605/using-midje-provided-in-a-let-clause-doesnt-stub-methods) has surprised us and others and I can't find anything about it in the wiki?

**Comment by marick** [comment]
What was surprising? Where did you look when you were surprised? - That would be the place to add the information.

**Comment by shmish111** [comment]
What suprised me was the fact that `provided` in a let clause doesn't work (see the link to SO I put in the comment).  I think a section specifically about `provided` would be nice, perhaps called `stubbing/mocking functions` or something similar?

**Comment by shmish111** [comment]
Also, I just noticed that in some of our tests we use `with-redefs` to do something more general than provided does, is there any mechanism in Midje for this that I don't know about?  The tests would look much nicer if it was also a `provided` of some type?

**Comment by marick** [comment]
Question: What should change in the [first page with a detailed section on `provided`](https://github.com/marick/Midje/wiki/Describing-one-checkable's-prerequisites) or in [this reference description](https://github.com/marick/Midje/wiki/Syntax-and-a-little-semantics#provided-prerequisites-for-a-single-checkable).

Before I can answer the question about `with-redefs`, I'd have to know what the "something more general" is.

**Comment by shmish111** [comment]
Sorry for the late reply.  I think just a note somewhere prominent that provided doesn't work if the result that required it was calculated in a let binding.  Also I think met-constants will do what I was doing with `with-redefs`.

**Comment by rafaeldff** [comment]
Fixed in https://github.com/marick/Midje/wiki/Syntax-and-a-little-semantics/_compare/65428721aef7f6ce1d6556edf4f031433fa23c23...f80592fd1143c1931ab237fa48b3c018e909a9e2 .
