### ISSUE TITLE
Tests don't terminate when an exception happens and an agent was used

### ISSUE THREAD

**Issue by vincentbernat** [marick/Midje#336]
Hey!

Here is a simple test case:

```clojure
(ns kalzone.clock-test
  (:use midje.sweet))

(facts "about mock clock"
  (fact "a schedule can be scheduled and triggered from a callback"
    (let [ticker (agent 0)]
      (send ticker inc))))

(facts "about something else"
  (fact "something else"
    (throw (ex-info "nooo" {}))))
```

When running, I get the exception and the tests don't terminate. If I put the `throw` into a test (like `=> anything`), the exception is correctly handled and the test terminate. I don't see an easy workaround as I cannot just call `shutdown-agents` whenever I get a problem since this cannot be reverted.

**Comment by vincentbernat** [comment]
Wrapping the facts in `deftest` works as expected. However, I am using `(change-defaults :print-level :print-facts)` and getting the output in sync with debug logs helps debugging issues. Using `deftest` enables some buffering for the stuff printed out by Midje: I get the debug outputs first, then the Midje output.

**Comment by vincentbernat** [comment]
In fact, this issue is a duplicate of #302.

**Comment by marick** [comment]
Sorry that I can't promise any fix any time soon.

**Comment by marick** [comment]
Closing this as a duplicate, but left a reminder to look here on the other issue
