### ISSUE TITLE
Suchwow depends on new Commons-codec

### ISSUE THREAD

**Issue by Deraen** [marick/Midje#337]
While this is not directly problem with Midje itself but suchwow, I'm opening this issue here as I think this might be quite common problem.

`such.random` ns depends on Commons-codec 1.7 for sha1Hex function: https://github.com/marick/suchwow/blob/master/src/such/random.clj#L17

This is problematic as `ring-codec` still uses old `commons-codec` https://github.com/ring-clojure/ring-codec/blob/master/project.clj#L7 and because how Maven dependencies work, it's quite probable that the version from `ring-codec` will be used. Maven will use closest dependency, e.g., `compojure` -> `ring-codec` -> `commons-codec` and `midje` -> `suchwow` -> `commons-codec`, the dependencies are on same level so the first one is used. As midje dependency is usually declared on dev profile, midje dependency will lose.

I'm not sure but this might be solvable by adding `commons-codec` dependency to `midje`. Then the dependency should be closer than the one from e.g. compojure.

**Comment by marick** [comment]
How about I have suchwow use commons-codec 1.6, so that it is the same as ring-codec? I'm sure there's no difference between the two for the use I make of it.

**Comment by Deraen** [comment]
That would also be a good solution :)

**Comment by Deraen** [comment]
Also, If you keep using sha1, there is a way to compute it without using commons-codec:

```clj
(import 'java.security.MessageDigest)
(String/format "%040x"
               (object-array [(BigInteger. 1 (.digest (doto (MessageDigest/getInstance "SHA-1")
                                                        (.reset)
                                                        (.update (.getBytes (pr-str {:foo "bar"}))))))]))
```

**Comment by marick** [comment]
Too late - I just pushed Midje 1.8.2, which uses commons-codec 1.6
