### ISSUE TITLE
Upgrading to 1.8.2 only downgrades dependencies

### ISSUE THREAD

**Issue by cch1** [marick/Midje#338]
For those of us working with pedantically specified dependencies, this is a step backwards.  Now I need to exclude the `midje` -> `commons-codec` transitive dependency in order to remain at 1.10, which is the version called for by `clj-http`, for example.  Why not require consumers that require 1.6 (or whatever older version of a transitive dependency for whatever reason) to manage that dependency on their own instead of slowing down midje's inclusion of up-to-date dependencies?

**Comment by marick** [comment]
I don't know how to satisfy both the people who dislike that Midje uses 1.10 because Compojure includes 1.6, or the people who dislike that Midje uses 1.6 because clj-http uses 1.10. 

I would like to make the largest number of people happy, which I thought would mean following Compojure's lead. 

I am assuming there's nothing Midje can do to satisfy both camps.

**Comment by cch1** [comment]
'I am assuming there's nothing Midje can do to satisfy both camps.'

Nope.  That's just the reality of working with third-party dependencies.  I think the only sane thing to do is to monotonically increase the versions of dependencies -never downgrade (modulo unworkable bugs).  By constantly updating dependencies you are riding the wave of generally improving software that most OSS users enjoy.

**Comment by marick** [comment]
Do you know if there's a reason Compojure uses an old version? Should I submit a pull request to upgrade it?

**Comment by marick** [comment]
I see it's indirect via:

```
 [ring/ring-codec "1.0.0"]
   [commons-codec "1.6"]
``

**Comment by marick** [comment]
I've filed a pull request against ring-codec

**Comment by cch1** [comment]
That's great, and I too would like to see ring updated.  But ultimately, it's unreasonable to expect all transitive dependencies to be in sync.  The larger the lib/app, the more difficult the task is.  Thankfully, with semantic versioning, leiningen's pedantic option and judicious exclusions, it not too hard to mange transitive dependencies yourself.  One monkey wrench in the scheme is when *increasing* a version actually causes a *decrease* in a transitive dependency.  That is ..unexpected and, modulo debilitating bugs, unecessary.  In the case of the commons codec transitive dependency mismatch, using exclusions on the midje would have been the preferred way for the complainant to deal with midje's upgrade to 1.10 of commons codec.  Instead, you are now stuck with trying to time the upgrade of midje's dependencies  so that one developer is happy.  What would have happened had 1.10 of commons-codec been necessary for a bug fix in midje?

**Comment by marick** [comment]
I'm actually trying to pick a version that provides the greatest good for the greatest number, which requires guessing whether more projects use compojure than clj-http or other more up-to-date dependencies. I guessed Compojure.

**Comment by cch1** [comment]
And what of all the other libraries that use commons-codec and might be used in conjunction with midje?  Why limit your investigation to compojure and clj-http?  My point (subtle, no?) is that *you* are not responsible for managing/optimizing my dependencies.  I have leiningen tooling for that.  What I hope from midje is consistency: semver (or some alternate, although semver vastly dominates in my experience), monotonically increasing dependencies, feature expansion (modulo well-documented deprecations), etc.

**Comment by marick** [comment]
Going forward, Midje releases will use the most recent versions of dependencies.
