### ISSUE TITLE
Code coverage?

### ISSUE THREAD

**Issue by Sh4pe** [marick/Midje#344]
What's the state of code coverage analysis with midje facts? Is it possible yet?

**Comment by marick** [comment]
I don't understand the question.

**Comment by Sh4pe** [comment]
Does midje provide means to obtain metrics on code coverage that show me which parts of my code are covered by tests and which parts are not? And if midje does not provide such means, how do you ensure that all code parts of your code are tested?

**Comment by marick** [comment]
It does not. 

I tend to not be overly concerned with code coverage. Disciplined TDD produces pretty high code coverage as a side effect. Given that discipline, code coverage provides a relatively weak signal about the quality of your tests. http://www.exampler.com/testing-com/writings/coverage.pdf

I speak from some experience on this, as I've written two code coverage tools for C and one (specialized) one for Java.

**Comment by marick** [comment]
See also [Experience with the cost of different coverage tools for testing ](http://www.testingeducation.org/BBST/foundations/Marick_experience.pdf)

**Comment by Sh4pe** [comment]
Wow, thanks for the hints and the links. Will read this :)

**Comment by idleherb** [comment]
If anyone is still looking on how to achieve this, you can do it with `lein cloverage --runner midje` (https://github.com/cloverage/cloverage).
