### ISSUE TITLE
Provided an array, no matter the order of its items

### ISSUE THREAD

**Issue by stephanebruckert** [marick/Midje#353]
I have the following and it works well to check that 3 items are passed to `batch-write-item`:

    (provided
      (batch-write-item cred
        :return-consumed-capacity "TOTAL"
        :return-item-collection-metrics "SIZE"
        :request-items {table-name [
          {:put-request {:item (test-helper/create-expected-scheduled-recording "test-recordingslist" 1454687100 "2001")}}
          {:put-request {:item (test-helper/create-expected-scheduled-recording "test-recordingslist" 1454687100 "2002")}}
          {:put-request {:item (test-helper/create-expected-scheduled-recording "test-recordingslist" 1454687100 "2003")}}
        ]}) => irrelevant :times 1)))

However in some situations the items 2001 2002 2003 could not be in that order and the test would fail. What can I do to say "These are the 3 items that will be passed to `batch-write-item`, but they can be passed in any order."?

    [
        {:put-request {:item (test-helper/create-expected-scheduled-recording "test-recordingslist" 1454687100 "2001")}}
        {:put-request {:item (test-helper/create-expected-scheduled-recording "test-recordingslist" 1454687100 "2002")}}
        {:put-request {:item (test-helper/create-expected-scheduled-recording "test-recordingslist" 1454687100 "2003")}}
    ]

Thanks

**Comment by marick** [comment]
Well, this is probably useless to you at this point, but here's my answer. Even complicated nested checkers can be used to describe valid arguments to prerequisite functions. So you can do the following. (I've simplified the data structure for clarity.)

```clojure
(defn batch-write-item [& args] "a real function goes here")

(defn function-under-test []
  (batch-write-item {:table-name [{:put-request "2002"}
                                  {:put-request "2001"}
                                  {:put-request "2003"}]})
  "do other stuff"
  8)

(fact
  (function-under-test) => 8
  (provided
    (batch-write-item
     (contains {:table-name (just [{:put-request "2002"}
                                   {:put-request "2001"}
                                   {:put-request "2003"}]
                                  :in-any-order)})) => irrelevant))

```

However, I recommend avoiding complicated inline checkers. Tests are more readable and maintainable when checkers are defined separately:

```clojure
(defchecker has-requests [& requests]
  (checker [actual]
     (contains {:table-name (just requests :in-any-order)})))

(fact
  (function-under-test) => 8
  (provided
    (batch-write-item (has-requests {:put-request "2002"}
                                    {:put-request "2001"}
                                    {:put-request "2003"})) => irrelevant))
```
