### ISSUE TITLE
Reflection warnings with *warn-on-reflection* true

### ISSUE THREAD

**Issue by blueberry** [marick/Midje#355]
WRT #299, which has been closed.

Midje uses reflection in many places. Since that happens in tests, it is not a critical flaw, but when production code that is being tested is evaluated with _warn-on-reflection_, midje spams the REPL or lein midje output with those reflection and boxing messages, obscuring the discovery and elimination of reflection messages in the production code.

The fix should not be too complicated - I guess that most of the time, it is a matter of including proper typehints. @marick  I am willing to fix most of these, just to not have to look at that wallpaper of reflection messages :), if such PR is welcome.

**Comment by marick** [comment]
Sorry for not responding to this. I would certainly merge such a pull request. Though there's something clearly wrong with the idea that test libraries have to adhere to production warnings.

**Comment by blueberry** [comment]
The intent of those tests would be exactly to ensure that there is no (unnecessary) boxing of numbers. IMHO, very important to all number crunching code. Currently, the testing libraries themselves produce lots of warnings that can mask warnings that the developer is interested at - those from the code under test.

**Comment by phillipm** [comment]
This has been addressed in https://github.com/marick/Midje/pull/415 (I think/hope)
That said, `suchwow` has some reflection warnings, and since Midje depends on it, you will still see some warnings. I'll fix those warnings sometime soon and release a new version of `suchwow`.
