### ISSUE TITLE
Keyword can not be used as function in `provided` clause

### ISSUE THREAD

**Issue by meowcakes** [marick/Midje#362]
Keywords implement `IFn`, so they can be used as a function on maps like so:

``` clojure
(:a {:a 1}) ; => 1
```

However if I try to do this in a `provided` clause like in this contrived example:

``` clojure
(def baz {:a 5})
(unfinished bar)
(defn foo [x] (even? (bar x)))
(fact "Oops"
  (foo 5) => true
  (provided (bar (:a baz)) => 6))
```

...an exception is generated, originating from here: https://github.com/marick/Midje/blob/master/src/midje/parsing/util/fnref.clj#L8
It appears to not consider keywords as a candidate for function classification.

I am using version 1.8.3

**Comment by meowcakes** [comment]
In fact this would extend to any form that evaluates to a callable but is neither a symbol nor sequential.

**Comment by marick** [comment]
I'm uncertain what the right solution is. In general, a form like `(provided (x (y ...)) => z` is expanded into two prerequisites:

```clojure
(provided 
  (y ...) => ..y-result-metaconstant..
  (x ..y-result-metaconstant..) => z
```

What should that actually mean when the token labeled `y` above is actually a keyword? Should it be ignored? If so, what would it mean if the "argument" to the keyword is actually a metaconstant? Should it be treated as a [data prerequisite](https://github.com/marick/Midje/wiki/Data-Prerequisites)? - even though data prerequisites haven't really proven to be very useful.

**Comment by phillipm** [comment]
fixed in https://github.com/marick/Midje/issues/393
