### ISSUE TITLE
Give reason for fail test

### ISSUE THREAD

**Issue by benjyz** [marick/Midje#365]
I've debugged midje by printing the reason for autotest fail here:

```(println (color/fail (str "reason : " t)))))```
https://github.com/marick/Midje/blob/master/src/midje/repl.clj#L530

**Comment by marick** [comment]
In the next alpha version of 1.9, Midje will print the message on the exception. If (1) that is inadequate, and (2) only the complete, lengthy stack trace helps, I urge you to file a bug against clojure.tools.namespace.

Too much of what Midje does is work around the bad error handling of official libraries. I'm tired of it.

**Comment by marick** [comment]
The new version (1.9.0-alpha6) tries to do better.
