### ISSUE TITLE
1.9.0 port

### ISSUE THREAD

**Issue by benjyz** [marick/Midje#366]
Are there any bigger issues for a 1.9.0 port? Since 1.9 introduced spec it would be nice to have it. one issue I had is addressed by #364

**Comment by marick** [comment]
I don't know. I'm shifting the bulk of my personal work to Elixir these days, though I do want to keep supporting Midje in the absence of anyone to take it over. 

My feelings about clojure.spec is... conflicted, having been in this space for many years.

**Comment by marick** [comment]
I have been keeping Midje up to date with the 1.9 releases.
