### ISSUE TITLE
midje.emission.plugins.junit should disable coloured output automatically

### ISSUE THREAD

**Issue by urzds** [marick/Midje#368]
Without explicitly specifying `:colorize false` in the Midje config, `midje.emission.plugins.junit` will output something like the following:

``` xml
<failure type=':actual-result-did-not-match-expected-value'>
<![CDATA[
^[[31mFAIL^[[0m "API - /api/v1 returns something" at (handler_test.clj:9)    Expected: 201      Actual: 200]]>
</failure>
```

This appears to confuse PHP's XML parser (ArcanistXUnitTestResultParser is unable to read this).

It would be nice if `midje.emission.plugins.junit` would automatically set `:colorize false` / disable coloured output. Alternatively, the emitters could operate on the raw data structures, with colorisation being applied as the last step.

**Comment by marick** [comment]
Could you supply a pull request?

**Comment by urzds** [comment]
PR in #376
