### ISSUE TITLE
Improvement on "migrating from clojure.test" tutorial

### ISSUE THREAD

**Issue by marick** [marick/Midje#370]
Mail thread

> Hi, just my two cents: I know it's trivial to follow the "setup and teardown" tutorial to migrate clojure.test fixtures to using midje, but it would be nice if this migration was covered in the migration tutorial.

---

> I'll put this on my todo list, but feel free to make a pull request

---

> I intended to, but I'm still strugling with what might be basic: `provided` stops working when I use `with-state-changes`. I still haven't had the chance to debug and understand if it's something I'm doing wrong or a bug in Midje, but until I find out idk if it's a good idea to try explaining "setup and teardown" to someone else, lol. You can say this is in my todo list as well...

**Comment by phillipm** [comment]
Updated https://github.com/marick/Midje/wiki/Migrating-from-clojure.test to include info on `with-state-changes` (see [this revision](https://github.com/marick/Midje/wiki/Migrating-from-clojure.test/_compare/001338902167e33b16f27507cf49722ccb6f4468...7f806135edc53cacf025d5da695350c4008882c9))
