### ISSUE TITLE
ExceptionInInitializerError when compiling 

### ISSUE THREAD

**Issue by rssole** [marick/Midje#373]
Hi, to be honest I am not really sure whether it is due to midje or my IDE environment (IDEA + Cursive) but when compiling some very simple namespace, exception trace is going down to midje.sweet:
`(ns internal.probing-fun-test
  (:require [internal.probing-fun :as pf])
  (:use midje.sweet))

(fact "Duplicates should be found"
      (pf/all-duplicates [4 3 2 7 8 2 3 1]) => [2 3])`

 I am getting exception below:

`Error:(1, 1) clojure: When compiling internal.probing-fun-test:
java.lang.ExceptionInInitializerError, compiling:(probing_fun_test.clj:1:1)
java.lang.NullPointerException: null
 at java.util.concurrent.ConcurrentHashMap.get (ConcurrentHashMap.java:936)
    clojure.lang.Namespace.find (Namespace.java:188)
    clojure.core$find_ns.invokeStatic (core.clj:4000)
    clojure.core$the_ns.invokeStatic (core.clj:4030)
    clojure.core$ns_name.invokeStatic (core.clj:4034)
    clojure.core$ns_name.invoke (core.clj:4034)
    midje.Bootstrap$bootstrap.invokeStatic (Bootstrap.clj:8)
    midje.Bootstrap$bootstrap.invoke (Bootstrap.clj:5)
    midje.sweet__init.load (:2)
    midje.sweet__init.<clinit> (:-1)`

Here is excerpt from my project.clj:

`:profiles {:dev {:dependencies [[midje "1.8.3"]]
                 :plugins [[lein-midje "3.2.1"]]}}`

Hopefully it will give you clue on possible issue or perhaps someone will be able to 
help in resolving if he/she faced the same problem already.

Cheers!

**Comment by marick** [comment]
Could you try it with a plain `lein midje` from the command line?

You might also try updating to the latest version of Midje (1.9.0-alpha6) - though I doubt it would make a difference.

**Comment by rssole** [comment]
Hi, yeah, sorry, I should have tried plain lein midje first before posting, but I am yet starting with midje. It works. Looks like it is something with Cursive because situation is better after Cursive update...

Sorry for an inconvenience I was perhaps mislead by stack trace :) (I know, excuses, excuses :) )
