### ISSUE TITLE
JUnit AfterClass equivalent in Midje Clojure?

### ISSUE THREAD

**Issue by ertugrulcetin** [marick/Midje#374]
I could not find any **Midje** function that runs after all facts.

**Here is the code:**

    (background
      (before :contents (println "Before All Facts"))
      (after :contents (println "After All Facts"))
      (before :facts (println "Before Each Fact"))
      (after :facts (println "After Each Fact")))

**Actual** Output is:

    Before All Facts
    After All Facts
    Before Each Fact
    After Each Fact

**Expected** Output is:

    Before All Facts
    Before Each Fact
    After Each Fact
    After All Facts

**Comment by marick** [comment]
That's unfortunate, but it's - as far as I know - unfixable. The Clojure file loader has no hook to let programs like Midje know when it's finished loading. 

This is part of the reason `background` is deprecated in current Midje's and hidden in the documentation: because `content` really means `right now`.

**Comment by ertugrulcetin** [comment]
@marick I can do it using **clojure.test/use-fixtures** with **:once** attribute like:

_Can't you just wrap it or something like that?_

```
(defn my-test-fixture [f]
  (println "Before Class")
  (f)
  (println "After Class"))

(use-fixtures :once my-test-fixture)
```

**Comment by marick** [comment]
Since I don't know clojure.test well, is `(use-fixtures :once...)` essentially running some code at the point of call? That is, would this work if the `use-fixtures` preceded the tests?

**Comment by ertugrulcetin** [comment]
Yes kinda, here is the following **clojure.test** code that does what I want:

```
(ns midje-examples.test-me
  (require [clojure.test :refer :all]))

(defn my-test-fixture
  [f]
  (println "Before Class")
  (f)
  (println "After Class"))

(defn my-test-fixture-test
  [f]
  (println "Before")
  (f)
  (println "After"))

(use-fixtures :once my-test-fixture)

(use-fixtures :each my-test-fixture-test)

(deftest test-one
  (is (= 1 1)))

(deftest test-two
  (is (= 1 1)))

(deftest test-three
  (is (= 1 1)))
```

**Output:**
Before Class
Before
After
Before
After
Before
After
After Class
