### ISSUE TITLE
How to check a map roughly

### ISSUE THREAD

**Issue by viebel** [marick/Midje#384]
Hi,

Wonderful lib!

I'd like to know how to check a map roughly.

Something like:
```clojure
(fact {:a 0.00002 :b 1} => (roughly {:a 0 :b 1})
```

But `roughly` accepts only number...

**Comment by rafaeldff** [comment]
Hi @viebel, you can use midje's collection matchers such as:

```clojure
(fact {:a 1000.00002 :b 1} => (just {:a (roughly 1000) :b 1}))
```

**Comment by viebel** [comment]
Thanks @rafaeldff 
Do you know why the following doesn't work?

```clojure
{:a 1000.00002 :b 1} => (just {:a (roughly 1000) :b 1})
```

**Comment by marick** [comment]
I just tried that (but not with the latest Midje), and it worked:

```
user=> (fact {:a 1000.00002 :b 1} => (just {:a (roughly 1000) :b 1}))
true
```

**Comment by viebel** [comment]
ok. cool
