### ISSUE TITLE
A way to check ex-data of a function that throws ExceptionInfo

### ISSUE THREAD

**Issue by weixunter** [marick/Midje#385]
```
(defn fail [])

(fact (fail) => (throws clojure.lang.ExceptionInfo "Message")
      (provided (fail) =throws=> (ex-info "Message" {:data "1"})))
=> true
```

How do I also check the ex-data where 
data = 1

**Comment by rafaeldff** [comment]
I'm not aware of a built-in support specifically ex-info/ex-data, but it's easy to inspect exception objects by passing a predicate as the last parameter to `throws`:

```
```

**Comment by wilkerlucio** [comment]
On a complement to rafael solution, a simple checker to use on those cases:

```
(defn assert-ex-info [message data]
  (fn [ex]
    (and (= message (.getMessage ex))
         (= data (ex-data ex)))))

(fact
  (something) => (throws ExceptionInfo (assert-ex-info "Some Error" {:error :data})
```

**Comment by phillipm** [comment]
I've updated the docs to include examples of how to do this: https://github.com/marick/Midje/wiki/Checkers
