### ISSUE TITLE
(autotest :filter :guard) change to (autotest :filter :some2)    Constant death cycle

### ISSUE THREAD

**Issue by xingzhefeng** [marick/Midje#426]
version clojure 1.9 midje 1.9  win10 + idea +cursive

when repl  change  autotest :filter  . the test  Continuous output . death cycle excute .

**Comment by xingzhefeng** [comment]
make do with (autotest :stop) very change time

**Comment by phillipm** [comment]
Glad you found a workaround

I'm happy to look into it further if you provide minimal reproduction steps.

In this case it would be helpful if you included a snippet of code that defines two facts with different metadata tags to be filtered by, and then the `autotest` commands you run to trigger the death cycle
