### ISSUE TITLE
Print namespaces of test that failed in the sumary

### ISSUE THREAD

**Issue by claynon** [marick/Midje#443]
When I run `lein midje` and the output of failed tests are too it's hard to find out which namespaces have tests that failed.
So it would be nice to have this list of namespace in the end sumary
Nowadays the sumary looks like this:

> FAILURE: 7 checks failed.  (But 193 succeeded.)
Subprocess failed

It would be nice if it looked like this:
>FAILURE: 7 checks failed.  (But 193 succeeded.)
namespaces with failed tests:
project.foo.anteater-test
project.tapir-test
project.capybara-test
Subprocess failed

**Comment by caiorulli** [comment]
Hi, @claynon . Don't know if you still need it, but there's a configuration setting for that.
https://github.com/marick/Midje/wiki/Configuration-files
You can use `(change-defaults :visible-failure-namespace true)`.
