### ISSUE TITLE
Why pr-str for failure description?

### ISSUE THREAD

**Issue by WhittlesJr** [marick/Midje#453]
I had some multi-line descriptions for my facts, and I noticed that when they failed the newlines came out as a bunch of very ugly `\n`s and it was all on one line. I tracked it down to here:

https://github.com/marick/Midje/blob/afeb21778cd679bca77f3aebbc4435b6b4f5e529/src/midje/emission/plugins/util.clj#L186

I tried removing the `pr-str` and it prints exactly as I would want. 

Is there some benefit for using `pr-str` here that I'm not aware of?

**Comment by philomates** [comment]
Hey @WhittlesJr, sounds right and I don't see why it was there.

Can you see if https://github.com/marick/Midje/pull/454 looks right and I'll merge/deploy it?

**Comment by WhittlesJr** [comment]
Looks good to me! Thank you so much.

**Comment by philomates** [comment]
Deployed in midje `1.9.6`
