### ISSUE TITLE
System property to avoid test-on-load

### ISSUE THREAD

**Issue by vemv** [marick/Midje#482]
https://github.com/marick/Midje/issues/372, while closed, remains a real issue for users of various tools e.g. tools.namespace, Eastwood, refactor-nrepl, CIDER - anything "runtime based" really which is a pretty broad spectrum of choices today!

The issue suggests touching a .midje file, however that is a global side-effect that can easily alter a given user's actual preference.

So something like a Java `System` property would be cleaner.

Example use case:

* First, I `(System/setProperty "midje.test-on-load" "false")`
* Then, I run Eastwood analysis
* Finally, I set `(System/setProperty "midje.test-on-load" ,,,)` to whatever it was before.

Would you be so kind to implement this simple tweak?

Thanks - V

**Comment by philomates** [comment]
good idea! Would be really cool to be able to more easily use things like eastwood on codebases with midje tests. 

Does https://github.com/marick/Midje/pull/483 do the trick for you?

**Comment by philomates** [comment]
cool, deployed as `1.10.6`

**Comment by vemv** [comment]
This worked like a charm - I set the `"-Dmidje.check-after-creation=false"` property before running Eastwood and it no longer runs tests.

Thanks again!
