### ISSUE TITLE
Feature request: Show what didn't match

### ISSUE THREAD

**Issue by mwmitchell** [marick/Midje#50]
While having the result of a failing fact show what matched is useful, I often find that it's much more helpful to know what didn't.

For example:

(fact {:id 100 :name "midje"} => (just {:id number? :name string? :code string?}))

Would report with:

"matched: {:id number? :name string?}"

AND:

"did not match {:code string?}"

**Comment by marick** [comment]
This is supported, somewhat crudely, in 1.7+
