### ISSUE TITLE
Mocking java method calls

### ISSUE THREAD

**Issue by jevgeni** [marick/Midje#55]
I am trying to mock java calls using meta constants like this:

``` clojure
(ns midje.test.core
 (:use [midje.sweet]))

(defn write [socket message]
 (.write (.getOutputStream socket) (.getBytes message)))

(fact
 (write ...sock.. "hello") => nil
 (provided
   (.getOutputStream ..sock..) => System/out))
```

I expect that (.getOutputStream ..sock..) will be replaced with System/
out in the write function call. However, I get "java.lang.Exception:
Unable to resolve var: .getOutputStream in this context (core.clj:
10)"

Considering you know which functions are to be mocked:

``` clojure
(fact ...
 (provided
  (.toUpperCase ..meta..) => "LO"))
```

it should be possible to perform something like this during macro evaluation:

``` clojure
(gen-interface
 :name midje.Stub
 :methods [[toUpperCase [] String]])

(def stub
 (proxy [midje.Stub] []
  (toUpperCase [] "LO")))
```

(assuming that interface name is generated and there is some mechanism
to clean *compile-path*)

Then associate ..meta.. with this stub and use it like this:

``` clojure
user=> (.toUpperCase stub)
"LO"
```

**Comment by kalouantonis** [comment]
Is this still on the roadmap? If so, I vote +1

**Comment by marick** [comment]
I don't see this comment on the github site, but I really doubt it will ever happen. Sorry.

Antonis Kalou wrote:

**Comment by kalouantonis** [comment]
Yea, sorry for deleting, I didn't notice the day of the posts until after I commented. Thanks for your help.
