### ISSUE TITLE
Condensed syntax for (f anything anything anything) => anything :never

### ISSUE THREAD

**Issue by AlexBaranosky** [marick/Midje#56]
My instincts say this goes against the internal representation of all of Midje's source code, however I think a condensed syntax for verifying a function was never called in any way shape or form would be nice.

Instead of:

```clojure
(fact "if there are no due reminders, never sends any emails out" 
  (run-reminders [...recipients...]) => nil
  (provided
    (load-due-reminders anything) => []    
    (send-reminder-email anything anything) => anything :never))
```

It might be something like:

```clojure
(fact "if there are no due reminders, never sends any emails out"
  (run-reminders [...recipients...]) => nil
  (provided
    (load-due-reminders anything) => []
    (send-reminder-email ...)  :never))
```

Exact syntax is open to injection of alternate opinions etc.

I'm willing to look into this, if the feature makes sense.

**Comment by marick** [comment]
Adopting a policy of "if it hasn't happened by now, it will either happen in 2.0 or never", I'm closing this
