### ISSUE TITLE
Add diffs between actual and expected (maps, seqs, sets, etc...)

### ISSUE THREAD

**Issue by AlexBaranosky** [marick/Midje#91]
```clojure
(fact 
  {1 2 3 4 5 6 7 8 9 10} => {5 6 7 8 9 11 12 13 14 15})
```
Reports:

FAIL: at (t_sweet.clj:306)
    Expected: {5 6, 7 8, 9 11, 12 13, 14 15}
      Actual: {1 2, 3 4, 5 6, 7 8, 9 10}
FAILURE: 1 fact was not confirmed. (But 51 were.)

What if it reported this instead:

FAIL: at (t_sweet.clj:306)
    Expected: {5 6, 7 8, 9 11, 12 13, 14 15}
      Actual:     {1 2, 3 4, 5 6, 7 8, 9 10}
      Actual Differs from Expected:  - {9 11, 12 13, 14 15}
                                                         + {1 2, 3 4} 
FAILURE: 1 fact was not confirmed. (But 51 were.)

or something akin to that.

What do you think?

**Comment by marick** [comment]
This is somewhat supported in 1.7+, though better support would use the structural-typing library
